# Use an official R runtime as a parent image
FROM rocker/shiny:4.4
#  "shiny"

ENV USER=shiny

# Install system dependencies including those for tidyverse
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y \
    git libxml2-dev libmagick++-dev \
    wget libgomp1 \  
    libssl-dev \     
    make \
    pandoc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#    libcurl4-gnutls-dev \
#    libcurl4-openssl-dev \
# Install Blast
# FROM ncbi/blast:2.13.0

#RUN wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.13.0/ncbi-blast-2.13.0+-x64-linux.tar.gz -O /tmp/blast.tar.gz && \
#	tar zxvf /tmp/blast.tar.gz -C /opt/ && rm /tmp/blast.tar.gz

ENV PATH="/opt/ncbi-blast-2.13.0+/bin:${PATH}"

# Install Basic Utility R Packages
COPY install_packages.R /tmp/
RUN Rscript /tmp/install_packages.R && rm /tmp/install_packages.R

# Additional packages for logging and diagnosis
RUN R -e "install.packages('log4r')" \
    && R -e "install.packages('readr')" \
    && R -e "install.packages('RcppTOML')"


RUN rm -rf /srv/shiny-server/*
COPY /app/ /srv/shiny-server/
COPY .Renviron.template /srv/shiny-server/.Renviron
COPY shiny-customized.config /etc/shiny-server/shiny-server.conf

WORKDIR /srv/shiny-server/

# Ensure that the expected user is present in the container
RUN if id shiny > /dev/null 2>&1 && [ "$(id -u shiny)" -ne 999 ]; then \
        userdel -r shiny; \
        id -u 999 > /dev/null 2>&1 && userdel -r "$(id -un 999)"; \
    fi; \
    useradd -u 999 -m -s /bin/bash shiny; \
    chown -R shiny:shiny /srv/shiny-server/ /var/lib/shiny-server/ /var/log/shiny-server/

# Setup the data and rlogs directories
RUN mkdir /data \
    && mkdir /rlogs \
    && chown -R shiny:shiny /data /rlogs

# Other settings
USER shiny
EXPOSE 3838

CMD ["/usr/bin/shiny-server"]
